---
title: "NEWS"
author: "Chase Clark"
date: "October 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This release is more or less an entire re-write of IDBac, so... many, many changes.


### Structural Changes
This is likely the largest change and the most significant for anyone wanting to add-on or contribute to the codebase. 

While the first version of IDBac followed an valid paradigm for small Shiny apps (two files: server.r and ui.r), it became quickly apparent that it was an unsustainable and unscalable model for future development.

 New paradigms:
 - IDBac is an R package
   - Now IDBac is structured as a regular R-package. This means that significant computation and code chunks have been pulled out of server.r and are now located in the package's `R` directory. 
 - IDBac is testable
   - While methods for testing the interactivity of Shiny apps is still a little shaky, over the coming months ~~all~~  functions within the `R` directory should have a `testthat` test.
 
### Structural Changes (continued)

Prior to this release IDBac relied on the filesystem for storing and retrieving mzXML files, processed data, etc

 
 
### Algorithm changes (AKA Breaking results changes)

##### Peak Binning
The largest change here was that of how protein spectra are compared. The algorithm contained in MALDIquant and used by the old version of IDBac [binPeaks()](https://github.com/sgibb/MALDIquant/blob/master/R/binPeaks-functions.R) has some drwabacks:
 binPeaks() outline is [here](https://github.com/sgibb/MALDIquant/blob/master/man/binPeaks-functions.Rd)
  1. The "bins" will change depending on which samples are provided.
    - Given peak lists A, B, C.  You bin peaks from A and B and then, separately, bin peaks from A and C. The two resulting A peak lists are not comparable.
  2. It doesn't scale well
    - It is fairly slow
    - See # 1
    
##### PCA

Now performed via the irlba package which should make faster but will provide some differences to prcomp

##### Cosine Similarity

Now performed with the coop package which ia a fast and memory-efficient implementation.
    
#### MANs

Now there is the option to filter out isotopologues, leaving monoisotopic peaks.
We have reduced the resolution of the MANs because of the problems with mentioned above with MALDIquant's binning (also we wee noticing some other side effects of the binning)
  
  
  
### Additions


The second if not largest change is the way that IDBac handles data. Now everything is handled via SQL, with a SQLite driver.
"Raw data" (no matter if it is straight instrument-data, mzML/mzXML, or txt) is first converted to mzML using ProteoWizard's MSConvert (included in installation).




















    
    
    

