---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  ---
  
  
  
```{r}
#z<-igraph::as.undirected(igraph::graph_from_data_frame(smallMolNetworkDataFrame())))

```
  
```{r}
  clusters <- igraph::fastgreedy.community(z)

igraph::V(z)$color <- as.vector(IDBacApp::colorBlindPalette()[1:100])[clusters$membership]
```


```{r}


sigmajs() %>%
  sg_from_igraph(z) %>% 
  sg_force_start() %>% # start
  sg_nodes(nodes, id, size, color) %>%
  sg_edges(edges, id, source, target) %>%
  sg_force_stop(5000) %>% # stop after 5 seconds
  sg_drag_nodes() %>% 
   sg_export_svg() %>% 
  sg_button("force_start", "force", tag = htmltools::tags$button, position = "bottom")  
  # sg_button(
  #   "export_svg", # event to trigger
  #   class = "btn btn-default",
  #   "asdfsda",
  #   tag = htmltools::tags$button,
  #   tags$i(class = "fa fa-download")
  # )




```

